// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$1 from "./loaders/List/Sections.tsx";
import * as $$$$$$0 from "./sections/Gallery.tsx";
import * as $$$$$$1 from "./sections/Footer/Footer.tsx";
import * as $$$$$$2 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$3 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$4 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$5 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$6 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$7 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$8 from "./sections/Images/Carousel.tsx";
import * as $$$$$$9 from "./sections/Layout/Container.tsx";
import * as $$$$$$10 from "./sections/Layout/Grid.tsx";
import * as $$$$$$11 from "./sections/Layout/Flex.tsx";
import * as $$$$$$12 from "./sections/Layout/GridItem.tsx";
import * as $$$$$$13 from "./sections/Cards/ImageCardsCarousel.tsx";
import * as $$$$$$14 from "./sections/Cards/IconCardsCarouselWithImage.tsx";
import * as $$$$$$15 from "./sections/Cards/ImageCardsCarouselWithImage.tsx";
import * as $$$$$$16 from "./sections/Cards/IconCardsCarousel.tsx";
import * as $$$$$$17 from "./sections/Animation/Animation.tsx";
import * as $$$$$$18 from "./sections/Content/Hero.tsx";
import * as $$$$$$19 from "./sections/Content/Features.tsx";
import * as $$$$$$20 from "./sections/Content/Intro.tsx";
import * as $$$$$$21 from "./sections/Content/BlogPosts.tsx";
import * as $$$$$$22 from "./sections/Content/TextWithImage.tsx";
import * as $$$$$$23 from "./sections/Content/RichText.tsx";
import * as $$$$$$24 from "./sections/Content/Partners.tsx";
import * as $$$$$$25 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$26 from "./sections/Content/Logos.tsx";
import * as $$$$$$27 from "./sections/Content/CallToAction.tsx";
import * as $$$$$$28 from "./sections/Content/Table.tsx";
import * as $$$$$$29 from "./sections/Content/Faq.tsx";
import * as $$$$$$30 from "./sections/Content/Benefits.tsx";
import * as $$$$$$31 from "./sections/Content/ImageSection.tsx";
import * as $$$$$$32 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$33 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$34 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$35 from "./sections/Product/ProductInfo.tsx";
import * as $$$$$$36 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$37 from "./sections/Product/ImageGallerySlider.tsx";
import * as $$$$$$38 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$39 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$40 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$41 from "./sections/Product/NotFound.tsx";
import * as $$$$$$42 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$43 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$44 from "./sections/Miscellaneous/Slide.tsx";
import * as $$$$$$45 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$46 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$47 from "./sections/Theme/Theme.tsx";
import * as $$$$$$48 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$49 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$50 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$51 from "./sections/Header/Header.tsx";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";

const manifest = {
  "loaders": {
    "deco-sites/ttt-tavano/loaders/Layouts/ProductCard.tsx": $$$0,
    "deco-sites/ttt-tavano/loaders/List/Sections.tsx": $$$1,
  },
  "sections": {
    "deco-sites/ttt-tavano/sections/Animation/Animation.tsx": $$$$$$17,
    "deco-sites/ttt-tavano/sections/Cards/IconCardsCarousel.tsx": $$$$$$16,
    "deco-sites/ttt-tavano/sections/Cards/IconCardsCarouselWithImage.tsx":
      $$$$$$14,
    "deco-sites/ttt-tavano/sections/Cards/ImageCardsCarousel.tsx": $$$$$$13,
    "deco-sites/ttt-tavano/sections/Cards/ImageCardsCarouselWithImage.tsx":
      $$$$$$15,
    "deco-sites/ttt-tavano/sections/Category/CategoryBanner.tsx": $$$$$$2,
    "deco-sites/ttt-tavano/sections/Category/CategoryGrid.tsx": $$$$$$4,
    "deco-sites/ttt-tavano/sections/Category/CategoryList.tsx": $$$$$$3,
    "deco-sites/ttt-tavano/sections/Content/Benefits.tsx": $$$$$$30,
    "deco-sites/ttt-tavano/sections/Content/BlogPosts.tsx": $$$$$$21,
    "deco-sites/ttt-tavano/sections/Content/CallToAction.tsx": $$$$$$27,
    "deco-sites/ttt-tavano/sections/Content/Faq.tsx": $$$$$$29,
    "deco-sites/ttt-tavano/sections/Content/Features.tsx": $$$$$$19,
    "deco-sites/ttt-tavano/sections/Content/Hero.tsx": $$$$$$18,
    "deco-sites/ttt-tavano/sections/Content/ImageSection.tsx": $$$$$$31,
    "deco-sites/ttt-tavano/sections/Content/Intro.tsx": $$$$$$20,
    "deco-sites/ttt-tavano/sections/Content/Logos.tsx": $$$$$$26,
    "deco-sites/ttt-tavano/sections/Content/Partners.tsx": $$$$$$24,
    "deco-sites/ttt-tavano/sections/Content/RichText.tsx": $$$$$$23,
    "deco-sites/ttt-tavano/sections/Content/Table.tsx": $$$$$$28,
    "deco-sites/ttt-tavano/sections/Content/Testimonials.tsx": $$$$$$25,
    "deco-sites/ttt-tavano/sections/Content/TextWithImage.tsx": $$$$$$22,
    "deco-sites/ttt-tavano/sections/Footer/Footer.tsx": $$$$$$1,
    "deco-sites/ttt-tavano/sections/Gallery.tsx": $$$$$$0,
    "deco-sites/ttt-tavano/sections/Header/Header.tsx": $$$$$$51,
    "deco-sites/ttt-tavano/sections/Images/BannerGrid.tsx": $$$$$$6,
    "deco-sites/ttt-tavano/sections/Images/Carousel.tsx": $$$$$$8,
    "deco-sites/ttt-tavano/sections/Images/ImageGallery.tsx": $$$$$$7,
    "deco-sites/ttt-tavano/sections/Images/ShoppableBanner.tsx": $$$$$$5,
    "deco-sites/ttt-tavano/sections/Layout/Container.tsx": $$$$$$9,
    "deco-sites/ttt-tavano/sections/Layout/Flex.tsx": $$$$$$11,
    "deco-sites/ttt-tavano/sections/Layout/Grid.tsx": $$$$$$10,
    "deco-sites/ttt-tavano/sections/Layout/GridItem.tsx": $$$$$$12,
    "deco-sites/ttt-tavano/sections/Links/LinkTree.tsx": $$$$$$48,
    "deco-sites/ttt-tavano/sections/Links/Shortcuts.tsx": $$$$$$49,
    "deco-sites/ttt-tavano/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$42,
    "deco-sites/ttt-tavano/sections/Miscellaneous/CookieConsent.tsx": $$$$$$43,
    "deco-sites/ttt-tavano/sections/Miscellaneous/Slide.tsx": $$$$$$44,
    "deco-sites/ttt-tavano/sections/Newsletter/Newsletter.tsx": $$$$$$50,
    "deco-sites/ttt-tavano/sections/Product/ImageGalleryFrontBack.tsx":
      $$$$$$38,
    "deco-sites/ttt-tavano/sections/Product/ImageGallerySlider.tsx": $$$$$$37,
    "deco-sites/ttt-tavano/sections/Product/NotFound.tsx": $$$$$$41,
    "deco-sites/ttt-tavano/sections/Product/NotFoundChallenge.tsx": $$$$$$33,
    "deco-sites/ttt-tavano/sections/Product/ProductInfo.tsx": $$$$$$35,
    "deco-sites/ttt-tavano/sections/Product/ProductShelf.tsx": $$$$$$36,
    "deco-sites/ttt-tavano/sections/Product/ProductShelfTabbed.tsx": $$$$$$40,
    "deco-sites/ttt-tavano/sections/Product/SearchResult.tsx": $$$$$$34,
    "deco-sites/ttt-tavano/sections/Product/ShelfWithImage.tsx": $$$$$$39,
    "deco-sites/ttt-tavano/sections/Product/Wishlist.tsx": $$$$$$32,
    "deco-sites/ttt-tavano/sections/Social/InstagramPosts.tsx": $$$$$$46,
    "deco-sites/ttt-tavano/sections/Social/WhatsApp.tsx": $$$$$$45,
    "deco-sites/ttt-tavano/sections/Theme/Theme.tsx": $$$$$$47,
  },
  "apps": {
    "deco-sites/ttt-tavano/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/ttt-tavano/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/ttt-tavano",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
